// Alerts

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const EMPTY_ALERT = 'EMPTY_ALERT'

// Auth - Register
export const ARTIST_REGISTER_SUCCESS = 'ARTIST_REGISTER_SUCCESS'
export const ARTIST_REGISTER_FAIL = 'ARTIST_REGISTER_FAIL'
export const ENTERPRISE_REGISTER_SUCCESS = 'ENTERPRISE_REGISTER_SUCCESS'
export const ENTERPRISE_REGISTER_FAIL = 'ENTERPRISE_REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
